### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by sveba** [RaptorDE/evcc_status_display#2]
Hi,
ich möchte dein Projekt für SH1106 anpassen. Da benutze ich die U8g2-Lib und sie braucht XBMP-Byte-Arrays für die Icons. Kannst du mir sagen woher du deine Icons hast, damit ich sie in Gimp nach XBMP umwandeln kann? 

Vielen Dank

**Comment by RaptorDE** [comment]
Hi, die Icons sind abgewandte MDI Icons https://pictogrammers.com/library/mdi/. Ich habe die angepassten Bilder soeben hochgeladen.
