### ISSUE TITLE
Name eines angeschlossenen Fahrzeugs im Display "null"

### ISSUE THREAD

**Issue by ThiloGa** [RaptorDE/evcc_status_display#3]
Moin,

in der REST API findet sich "vehicleTitle" nicht mehr. 

Ändern auf "vehicleName" behebt das Problem.

Grüsse

**Comment by RaptorDE** [comment]
Vielen Dank für den Hinweis, ich habe eine angepassten Sketch hochgeladen.
https://raw.githubusercontent.com/RaptorDE/evcc_status_display/main/evcc_status_display_SSD1306_github_2024_03_24.ino
